# Generated by Django 5.2.3 on 2025-10-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verify_email_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verify_email',
            field=models.BooleanField(default=False, verbose_name='Подтверждение электронной почты'),
        ),
    ]
